version: '3.9'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: llmchecks
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+psycopg://postgres:postgres@db:5432/llmchecks
      LLM_PROVIDER: ${LLM_PROVIDER:-gemini}
      LLM_MODEL: ${LLM_MODEL:-gemini-1.5-flash}
      JUDGE_PROVIDER: ${JUDGE_PROVIDER:-gemini}
      JUDGE_MODEL: ${JUDGE_MODEL:-gemini-1.5-flash}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:8000
    ports:
      - "3000:3000"
    command: npm run dev
    depends_on:
      - backend

volumes:
  pgdata: